### ISSUE TITLE
请问为什么会出现这个错误？

### ISSUE THREAD

**Issue by hihaozhe** [xhlove/WVClient3#1]
![image](https://user-images.githubusercontent.com/63550512/98447788-8f529e00-2162-11eb-8f95-e44df3a4d84b.png)

**Comment by hihaozhe** [comment]
![image](https://user-images.githubusercontent.com/63550512/98454719-b761f180-21a2-11eb-87c1-03846c42ed83.png)

**Comment by xhlove** [comment]
exe不是我编译的，建议咨询原项目作者。
