### ISSUE TITLE
ImportError: DLL load failed while importing cdmapi: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Sentivet** [xhlove/WVClient3#10]
I am using python version 3.8.5 . Still getting "ImportError: DLL load failed while importing cdmapi: %1 is not a valid Win32 application" this error

**Comment by xbstory** [comment]
the pre-build lib is for x64, you need compile if for win32 manually

**Comment by Sentivet** [comment]
Thanks working fine now
