### ISSUE TITLE
Installation for Linux is not clear

### ISSUE THREAD

**Issue by dausruddin** [xhlove/WVClient3#11]
Hi. Can you elaborate the steps to install in Linux system?

I compiled cryptopp with `make` command. Now I got hundreds of files

<details>
  <summary>File list</summary>
<pre>
3way.cpp         bfinit.o          config_os.h               donna_64.o     gf2_32.h           kalyna.o         mqueue.cpp      randpool.cpp       secblockfwd.h      sm4_simd.cpp       validat2.cpp
3way.h           blake2b_simd.cpp  config_ver.h              donna.h        gf2_32.o           kalynatab.cpp    mqueue.h        randpool.h         secblock.h         sm4_simd.o         validat2.o
3way.o           blake2b_simd.o    cpu.cpp                   donna_sse.cpp  gf256.cpp          kalynatab.o      mqueue.o        randpool.o         seckey.h           smartptr.h         validat3.cpp
adhoc.cpp        blake2.cpp        cpu.h                     donna_sse.h    gf256.h            keccak_core.cpp  mqv.cpp         rc2.cpp            Security.md        sosemanuk.cpp      validat3.o
adhoc.cpp.proto  blake2.h          cpu.o                     donna_sse.o    gf256.o            keccak_core.o    mqv.h           rc2.h              seed.cpp           sosemanuk.h        validat4.cpp
adhoc.o          blake2.o          crc.cpp                   Doxyfile       gf2n.cpp           keccak.cpp       mqv.o           rc2.o              seed.h             sosemanuk.o        validat4.o
adler32.cpp      blake2s_simd.cpp  crc.h                     drbg.h         gf2n.h             keccak.h         naclite.h       rc5.cpp            seed.o             speck128_simd.cpp  validat5.cpp
adler32.h        blake2s_simd.o    crc.o                     dsa.cpp        gf2n.o             keccak.o         nbtheory.cpp    rc5.h              serpent.cpp        speck128_simd.o    validat5.o
adler32.o        blowfish.cpp      crc_simd.cpp              dsa.h          gf2n_simd.cpp      keccak_simd.cpp  nbtheory.h      rc5.o              serpent.h          speck.cpp          validat6.cpp
adv_simd.h       blowfish.h        crc_simd.o                dsa.o          gf2n_simd.o        keccak_simd.o    nbtheory.o      rc6.cpp            serpent.o          speck.h            validat6.o
aes_armv4.h      blowfish.o        cryptdll.vcxproj          eax.cpp        gfpcrypt.cpp       lea.cpp          neon_simd.cpp   rc6.h              serpentp.h         speck.o            validat7.cpp
aes_armv4.S      blumshub.cpp      cryptdll.vcxproj.filters  eax.h          gfpcrypt.h         lea.h            nr.h            rc6.o              sha1_armv4.h       square.cpp         validat7.o
aes.h            blumshub.h        cryptest.exe              eax.o          gfpcrypt.o         lea.o            oaep.cpp        rdrand.asm         sha1_armv4.S       square.h           validat8.cpp
algebra.cpp      blumshub.o        cryptest.nmake            ec2n.cpp       GNUmakefile        lea_simd.cpp     oaep.h          rdrand.cpp         sha256_armv4.h     square.o           validat8.o
algebra.h        camellia.cpp      cryptest.sln              ec2n.h         GNUmakefile-cross  lea_simd.o       oaep.o          rdrand.h           sha256_armv4.S     squaretb.cpp       validat9.cpp
algebra.o        camellia.h        cryptest.vcxproj          ec2n.o         gost.cpp           libcryptopp.a    oids.h          rdrand.o           sha3.cpp           squaretb.o         validat9.o
algparam.cpp     camellia.o        cryptest.vcxproj.filters  eccrypto.cpp   gost.h             License.txt      osrng.cpp       rdseed.asm         sha3.h             sse_simd.cpp       validate.h
algparam.h       cast.cpp          cryptest.vcxproj.user     eccrypto.h     gost.o             lsh256_avx.cpp   osrng.h         rdtables.cpp       sha3.o             sse_simd.o         vc60.zip
algparam.o       cast.h            cryptlib.cpp              eccrypto.o     gzip.cpp           lsh256_avx.o     osrng.o         rdtables.o         sha512_armv4.h     stdcpp.h           vmac.cpp
allocate.cpp     cast.o            cryptlib.h                ecp.cpp        gzip.h             lsh256.cpp       ossig.h         Readme.txt         sha512_armv4.S     strciphr.cpp       vmac.h
allocate.h       casts.cpp         cryptlib.o                ecp.h          gzip.o             lsh256.o         padlkrng.cpp    regtest1.cpp       shacal2.cpp        strciphr.h         vmac.o
allocate.o       casts.o           cryptlib.vcxproj          ecp.o          hashfwd.h          lsh256_sse.cpp   padlkrng.h      regtest1.o         shacal2.h          strciphr.o         vs2005.zip
arc4.cpp         cbcmac.cpp        cryptlib.vcxproj.filters  ecpoint.h      hc128.cpp          lsh256_sse.o     padlkrng.o      regtest2.cpp       shacal2.o          tea.cpp            wake.cpp
arc4.h           cbcmac.h          cryptopp.mapfile          elgamal.cpp    hc128.h            lsh512_avx.cpp   panama.cpp      regtest2.o         shacal2_simd.cpp   tea.h              wake.h
arc4.o           cbcmac.o          cryptopp.rc               elgamal.h      hc128.o            lsh512_avx.o     panama.h        regtest3.cpp       shacal2_simd.o     tea.o              wake.o
argnames.h       ccm.cpp           cryptopp.supp             elgamal.o      hc256.cpp          lsh512.cpp       panama.o        regtest3.o         sha.cpp            test.cpp           whrlpool.cpp
aria.cpp         ccm.h             darn.cpp                  emsa2.cpp      hc256.h            lsh512.o         pch.cpp         regtest4.cpp       sha.h              TestData           whrlpool.h
aria.h           ccm.o             darn.h                    emsa2.h        hc256.o            lsh512_sse.cpp   pch.h           regtest4.o         shake.cpp          test.o             whrlpool.o
aria.o           chacha_avx.cpp    darn.o                    emsa2.o        hex.cpp            lsh512_sse.o     pkcspad.cpp     resource.h         shake.h            TestPrograms       words.h
aria_simd.cpp    chacha_avx.o      datatest.cpp              eprecomp.cpp   hex.h              lsh.h            pkcspad.h       rijndael.cpp       shake.o            TestScripts        x64dll.asm
aria_simd.o      chacha.cpp        datatest.o                eprecomp.h     hex.o              lubyrack.h       pkcspad.o       rijndael.h         sha.o              TestVectors        x64masm.asm
ariatab.cpp      chacha.h          default.cpp               eprecomp.o     hight.cpp          luc.cpp          poly1305.cpp    rijndael.o         sharkbox.cpp       tftables.cpp       xed25519.cpp
ariatab.o        chacha.o          default.h                 esign.cpp      hight.h            luc.h            poly1305.h      rijndael_simd.cpp  sharkbox.o         tftables.o         xed25519.h
arm_simd.h       chachapoly.cpp    default.o                 esign.h        hight.o            luc.o            poly1305.o      rijndael_simd.o    shark.cpp          threefish.cpp      xed25519.o
asn.cpp          chachapoly.h      des.cpp                   esign.o        History.txt        mars.cpp         polynomi.cpp    ripemd.cpp         shark.h            threefish.h        xtr.cpp
asn.h            chachapoly.o      des.h                     factory.h      hkdf.h             mars.h           polynomi.h      ripemd.h           shark.o            threefish.o        xtrcrypt.cpp
asn.o            chacha_simd.cpp   des.o                     fhmqv.h        hmac.cpp           mars.o           polynomi.o      ripemd.o           sha_simd.cpp       tiger.cpp          xtrcrypt.h
authenc.cpp      chacha_simd.o     dessp.cpp                 Filelist.txt   hmac.h             marss.cpp        ppc_power7.cpp  rng.cpp            sha_simd.o         tiger.h            xtrcrypt.o
authenc.h        cham.cpp          dessp.o                   files.cpp      hmac.o             marss.o          ppc_power8.cpp  rng.h              simeck.cpp         tiger.o            xtr.h
authenc.o        cham.h            dh2.cpp                   files.h        hmqv.h             md2.cpp          ppc_power9.cpp  rng.o              simeck.h           tigertab.cpp       xtr.o
base32.cpp       cham.o            dh2.h                     files.o        hrtimer.cpp        md2.h            ppc_simd.cpp    rsa.cpp            simeck.o           tigertab.o         xts.cpp
base32.h         cham_simd.cpp     dh2.o                     filters.cpp    hrtimer.h          md2.o            ppc_simd.h      rsa.h              simon128_simd.cpp  trap.h             xts.h
base32.o         cham_simd.o       dh.cpp                    filters.h      hrtimer.o          md4.cpp          pssr.cpp        rsa.o              simon128_simd.o    trunhash.h         xts.o
base64.cpp       channels.cpp      dh.h                      filters.o      ida.cpp            md4.h            pssr.h          rw.cpp             simon.cpp          ttmac.cpp          zdeflate.cpp
base64.h         channels.h        dh.o                      fips140.cpp    ida.h              md4.o            pssr.o          rw.h               simon.h            ttmac.h            zdeflate.h
base64.o         channels.o        dll.cpp                   fips140.h      ida.o              md5.cpp          pubkey.cpp      rw.o               simon.o            ttmac.o            zdeflate.o
basecode.cpp     cmac.cpp          dll.h                     fips140.o      idea.cpp           md5.h            pubkey.h        safer.cpp          simple.cpp         tweetnacl.cpp      zinflate.cpp
basecode.h       cmac.h            dll.o                     fipsalgt.cpp   idea.h             md5.o            pubkey.o        safer.h            simple.h           tweetnacl.h        zinflate.h
basecode.o       cmac.o            dlltest.cpp               fipsalgt.o     idea.o             mdc.h            pwdbased.h      safer.o            siphash.h          tweetnacl.o        zinflate.o
bds10.zip        config_align.h    dlltest.o                 fipstest.cpp   Install.txt        mersenne.h       queue.cpp       salsa.cpp          skipjack.cpp       twofish.cpp        zlib.cpp
bench1.cpp       config_asm.h      dlltest.vcxproj           fipstest.o     integer.cpp        misc.cpp         queue.h         salsa.h            skipjack.h         twofish.h          zlib.h
bench1.o         config_cpu.h      dlltest.vcxproj.filters   fltrimpl.h     integer.h          misc.h           queue.o         salsa.o            skipjack.o         twofish.o          zlib.o
bench2.cpp       config_cxx.h      dmac.h                    gcm.cpp        integer.o          misc.o           rabbit.cpp      scrypt.cpp         sm3.cpp            validat0.cpp
bench2.o         config_dll.h      donna_32.cpp              gcm.h          iterhash.cpp       modarith.h       rabbit.h        scrypt.h           sm3.h              validat0.o
bench3.cpp       config.h          donna_32.h                gcm.o          iterhash.h         modes.cpp        rabbit.o        scrypt.o           sm3.o              validat10.cpp
bench3.o         config_int.h      donna_32.o                gcm_simd.cpp   iterhash.o         modes.h          rabin.cpp       seal.cpp           sm4.cpp            validat10.o
bench.h          config_misc.h     donna_64.cpp              gcm_simd.o     kalyna.cpp         modes.o          rabin.h         seal.h             sm4.h              validat1.cpp
bfinit.cpp       config_ns.h       donna_64.h                gf2_32.cpp     kalyna.h           modexppc.h       rabin.o         seal.o             sm4.o              validat1.o
</pre>
</details>

My questions:

  1. Which file do I need to copy to `cdmapi-python-extension-src`?
  2. What do I put in **extra_objects**?
  3. Do I still need to run `python setup.py build_ext --inplace` after that?

Thank you.

**Comment by xbstory** [comment]
1. copy libcryptopp.a to cdmapi-python-extension-src
2. put libcryptopp.a in extra_objects
3. yes

**Comment by dausruddin** [comment]
Okay, done.

After that I moved `cdmapi.cpython-39-x86_64-linux-gnu.so` to `pywidevine/cdm/cdmapi.pyd`. 
Is this correct?

Currently getting this error when running `$ python wvclient.py -h`

```
Traceback (most recent call last):
  File "/home/john/others/WVClient3/wvclient.py", line 8, in <module>
    from pywidevine.decrypt.wvdecrypt import WvDecrypt
  File "/home/john/others/WVClient3/pywidevine/decrypt/wvdecrypt.py", line 3, in <module>
    from pywidevine.cdm import cdm, deviceconfig
  File "/home/john/others/WVClient3/pywidevine/cdm/cdm.py", line 21, in <module>
    from pywidevine.cdm import cdmapi
ImportError: cannot import name 'cdmapi' from 'pywidevine.cdm' (/home/john/others/WVClient3/pywidevine/cdm/__init__.py)
```

**Comment by xbstory** [comment]
.pyd is for win, you need rename it to cdmapi.so

**Comment by dausruddin** [comment]
Thank you. Got it working

These are  the steps required.

  1. Download source for [WVClient3](https://github.com/xhlove/WVClient3/) and [cryptopp](https://github.com/weidai11/cryptopp)
  2. Compile cryptopp by running `make`
  3. Copy compiled cryptopp library `libcryptopp.a` to folder `cdmapi-python-extension-src`
  4. Go to `cdmapi-python-extension-src` and run `$ python setup.py build_ext --inplace` 
  5. Copy and rename `cdmapi.cpython-39-x86_64-linux-gnu.so` to `pywidevine/cdm/cdmapi.so`
