### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TiRajo** [xhlove/WVClient3#3]
it works well but gives the wrong key. how to get the exact key? any guide

**Comment by xhlove** [comment]
where is the proof ?

its same as widevine-l3-guesser result.

![image](https://user-images.githubusercontent.com/48152166/127801586-d79e31c2-b2d9-44eb-8341-304c9132b857.png)

**Comment by TiRajo** [comment]
widevine-l3-guesse not gives result as its shaka i tried with yours decrypt not works

**Comment by xhlove** [comment]
I think you should specific `--license-url` option

**Comment by TiRajo** [comment]
this is result with amazon prime . 

--init-path (even kid is wrong)
![Capture](https://user-images.githubusercontent.com/88180312/127803377-83d1ca06-b2d8-443f-96fb-d87d655c2577.PNG)

--mpd-url(not works gives error)
![Capture2](https://user-images.githubusercontent.com/88180312/127803663-8244b11b-7323-4142-b5a8-c926053bbc32.PNG)

 --license-url i dont know how to take license url

**Comment by xhlove** [comment]
chrome f12, filter license keyword at Network tab

**Comment by xhlove** [comment]
not sure what is lack, such as headers ?

**Comment by TiRajo** [comment]
C:\Users\91979>**wvclient.py --mpd-url "https://s3-bom-ww.cf.dash.row.aiv-cdn.net/dm/2$WdfaSOkHgWn5dTw0xCrp6uBUad0~/2966/bf9f/470f/4178-8ae5-3bc5cf2af5f6/55baa540-9cf0-4b98-a240-5e2929c9c166_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase" --license-url "http://widevine-proxy.appspot.com/proxy"**
Traceback (most recent call last):
  File "C:\Users\91979\Downloads\Compressed\WVClient3-main\WVClient3-main\wvclient.py", line 142, in <module>
    main(args)
  File "C:\Users\91979\Downloads\Compressed\WVClient3-main\WVClient3-main\wvclient.py", line 128, in main
    cdm.work(pssh)
  File "C:\Users\91979\Downloads\Compressed\WVClient3-main\WVClient3-main\wvclient.py", line 106, in work
    license_request_data = self.generateRequestData(pssh)
  File "C:\Users\91979\Downloads\Compressed\WVClient3-main\WVClient3-main\wvclient.py", line 75, in generateRequestData
    recv = self._socket.recv(10240)
socket.timeout: timed out

**Comment by xhlove** [comment]
ONLY WORK FOR PART WEBSITE

**Comment by Sentivet** [comment]
> widevine-l3-guesse not gives result as its shaka i tried with yours gives key but decrypt not works
> 
> C:\Users\919\WVClient3-main\WVClient3-main\wvclient.py --mpd-url https://jiovod.wdrm.cdn.jio.com/content/entry/wvdata/42/20/9288ac308d5111eb8240bd4a25cab33d_HD_WEBDESKTOP_A_1616784003306.mpd?jct=wVpiHMjPcv8jgWeCo48lpQ&pxe=1627885527&st=b89d5a922de70544b0ba47917189c24c
> KID:KEY 67ff6164da355f2f896ccc04624c8738:6bc8e7be8c875330aa9701e9aad26edb
> KID:KEY 340c439c2e255307a7d2ee5be4981922:98d88497f7604a2958082e794eb00195
> KID:KEY 041fd988bd885b7fb6756a573b97fcc3:0a98a71556aae4fa86b378b0e3319a96

Have you found a way to get keys for jiocinema?

**Comment by Sentivet** [comment]
> > widevine-l3-guesse not gives result as its shaka i tried with yours gives key but decrypt not works
> > C:\Users\919\WVClient3-main\WVClient3-main\wvclient.py --mpd-url https://jiovod.wdrm.cdn.jio.com/content/entry/wvdata/42/20/9288ac308d5111eb8240bd4a25cab33d_HD_WEBDESKTOP_A_1616784003306.mpd?jct=wVpiHMjPcv8jgWeCo48lpQ&pxe=1627885527&st=b89d5a922de70544b0ba47917189c24c
> > KID:KEY 67ff6164da355f2f896ccc04624c8738:6bc8e7be8c875330aa9701e9aad26edb
> > KID:KEY 340c439c2e255307a7d2ee5be4981922:98d88497f7604a2958082e794eb00195
> > KID:KEY 041fd988bd885b7fb6756a573b97fcc3:0a98a71556aae4fa86b378b0e3319a96
> 
> Have you found a way to get keys for jiocinema?

And how to find license url for a specific site?

> chrome f12, filter license keyword at Network tab
This method not working for jiocinema.com site. So any other way to find license url?
